### ISSUE TITLE
Support latest ember-template-lint and prettier

### ISSUE THREAD

**Issue by timiyay** [ember-template-lint/ember-template-lint-plugin-prettier#146]
[Ember Times 180 announced Handlebars support for `prettier`](https://blog.emberjs.com/the-ember-times-issue-180/), and recommended that folks use this repo to integrate it.

This repo defines `peerDependencies` for outdated major versions of both `ember-template-lint@2` and `prettier@1`. The latest versions are `ember-template-lint@3.4.2` and `prettier@2.3.0`.

From my own experimentation, this repo works fine with the latest major versions, so it may only be the peer dependency ranges that need altering.

**Comment by dcyriller** [comment]
Thanks for the report @timiyay! There is a PR ongoing: https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/pull/127. Once merged, I'll cut a new release.

**Comment by dcyriller** [comment]
v2.0.1 fixes the issue
