### ISSUE TITLE
Update documentation to no longer say Prettier support is experimental

### ISSUE THREAD

**Issue by rahulk94** [ember-template-lint/ember-template-lint-plugin-prettier#160]
The quest to add Handlebars support in to Prettier is now complete https://github.com/jgwhite/prettier/issues/1#issuecomment-848859850.

The documentation in this repo should be updated to reflect this as the HBS support is no longer experimental. There may be some dependency changes that can be done at the same time to enforce usage of the officially compatible Prettier versions.

**Comment by dcyriller** [comment]
done! thanks @rahulk94
