### ISSUE TITLE
`Delete ⏎⏎⏎⏎⏎⏎⏎⏎⏎⏎⏎····················· (fixable)` always appears in test files

### ISSUE THREAD

**Issue by charlesfries** [ember-template-lint/ember-template-lint-plugin-prettier#168]
`Delete ⏎⏎⏎⏎⏎⏎⏎⏎⏎⏎⏎····················· (fixable)`

Every single one of my app's test files shows this VSCode error at position [1, 1]. Clicking "fix" causes the entire test code to be laid out on a single line. If I disable `ember-template-lint-plugin-prettier` in `.template-lintrc.js` the error goes away. It only happens in test files, and furthermore it only appears in VSCode's "Problems" drawer--it does not appear in the CLI after linting. 

Is anything else seeing this?

```
DEBUG: -------------------------------
DEBUG: Ember             : 3.25.4
DEBUG: Ember Data        : 3.25.0
DEBUG: Ember Simple Auth : 3.1.0
DEBUG: Model Fragments   : 5.0.0-beta.2
DEBUG: -------------------------------
```

```js
// .template-lintrc.js

'use strict';

module.exports = {
  plugins: ['ember-template-lint-plugin-prettier'],
  extends: ['recommended', 'ember-template-lint-plugin-prettier:recommended'],
};
```

```js
// .prettierrc.js

'use strict';

module.exports = {
  singleQuote: true,
  printWidth: 300,
  overrides: [
    {
      files: '*.hbs',
      options: {
        singleQuote: false,
      },
    },
  ],
};
```

![Screenshot 2021-09-02 140502](https://user-images.githubusercontent.com/2275005/131916110-d436baa1-0c29-4160-902d-7c4fb557c10a.png)

**Comment by dcyriller** [comment]
Thanks for the detailed report @charlesfries!

The bug has to be found somewhere between the VSCode extension you use ([vscode-ember](https://github.com/lifeart/vscode-ember) I assume) and this plugin.

ember-template-lint by itself doesn't support linting js / ts files (at least not as of today). So, I think the editor extension parses the ts file to find hbs snippets (and then lints them).

I have tried to reproduce this issue - with no luck (it is hard for me I'm not a VSCode user). Could you try to post in [vscode-ember](https://github.com/lifeart/vscode-ember) to get a second look?

**Comment by josemarluedke** [comment]
I have the same issue but I use neovim with the ember lang server and this plugin.

**Comment by charlesfries** [comment]
Solution found in https://github.com/lifeart/vscode-ember/issues/22
