### ISSUE TITLE
Add release-it setup

### ISSUE THREAD

**Issue by scalvert** [ember-template-lint/ember-template-lint-plugin-prettier#180]
@dcyriller how would you feel about my adding `release-it` to this repo? We use it for most of our other repos, and it makes releasing really easy. I'm happy to add it.

**Comment by dcyriller** [comment]
It would be a great addition! In fact, I drafted this PR a couple hours ago: https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/pull/179. I don’t have a lot of experience using release-it. What do you think of it?

**Comment by scalvert** [comment]
Looks awesome. I left one comment. 👍

**Comment by dcyriller** [comment]
Just released a patch version to test that it works as expected. The setup is very convenient! Thanks a lot for you help @scalvert.

**Comment by scalvert** [comment]
For sure! Happy to help.
