### ISSUE TITLE
Shouldn't the `no-whitespace-for-layout` be disabled by this plugin?

### ISSUE THREAD

**Issue by boris-petrov** [ember-template-lint/ember-template-lint-plugin-prettier#184]
I believe it conflicts with Prettier, am I not right?

**Comment by dcyriller** [comment]
Thank you @boris-petrov for opening this issue.

The rule is indeed in ember-template-lint's `stylistic` config. And generally we prefer to disable the stylistic rules to use this plugin. For example, `block-indentation` or `quotes` 100% conflict with how Prettier formats the template.

However, in that case, I wonder if we should not remove the `no-whitespace-for-layout` rule from the `stylistic` config. Indeed, `no-whitespace-for-layout` seems to be a stylistic rule regarding the css style, but not regarding the code style (double quotes, final newline etc.). I have opened https://github.com/ember-template-lint/ember-template-lint/issues/2183 to continue the discussion in ember-template-lint.

(If you have a concrete example of conflict, I'd be glad to take a look!)

**Comment by boris-petrov** [comment]
@dcyriller - thanks for the answer! I got confused about the meaning of `no-whitespace-for-layout`, sorry. It absolutely doesn't conflict with Prettier and shouldn't be touched by this plugin here. Sorry for the confusion!

As for whether it shouldn't be in the `stylistic`... I guess it makes sense to be. I would leave it there.
