### ISSUE TITLE
Single quotes inside curlies and double quotes outside is not possible

### ISSUE THREAD

**Issue by VincentMolinie** [ember-template-lint/ember-template-lint-plugin-prettier#186]
Do you plan to support this kind of usecase:
```hbs
<div class="my-class {{if this.isActive 'my-class--modifier'}}">
</div>
```

This is supported by eslint but it conflicts with prettier 😅. Is there a way to disable the rule on prettier or to support it.

If I can help please let me know 😉

**Comment by dwickern** [comment]
> ```hbs
> <div class="my-class {{if this.isActive 'my-class--modifier'}}">
> </div>
> ```
That's the default now since prettier 2.5.0 (https://github.com/prettier/prettier/pull/11524).

With `singleQuote: true` they are inverted:
> ```hbs
> <div class='my-class {{if this.isActive "my-class--modifier"}}'>
> </div>
> ```

On prior versions you would get all double-quotes (or all single-quotes with `singleQuote: true`).

**Comment by dcyriller** [comment]
Thanks a lot for the info @dwickern! I am closing the issue since the feature is implemented.
