### ISSUE TITLE
Support ember-template-lint v5

### ISSUE THREAD

**Issue by bmish** [ember-template-lint/ember-template-lint-plugin-prettier#236]
First alpha of ember-template-lint v5 is out: https://github.com/ember-template-lint/ember-template-lint/releases/tag/v5.0.0-alpha.0

The work is being tracked in: https://github.com/ember-template-lint/ember-template-lint/issues/2319

**Comment by bertdeblock** [comment]
Do we want a release that supports both `ember-template-lint` v4 and v5?
Unrelated, it seems we could also update the supported Node engines:
https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/blob/main/package.json#L54.

**Comment by bmish** [comment]
Yes, I don't see why this plugin needs to be limited to a single major version of ember-template-lint. I think we can change the peer dependency to `"ember-template-lint": ">= 4.0.0"` as v4 and all subsequent versions will be ESM and unlikely to have compatibility issues.

**Comment by bmish** [comment]
Released: https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/releases/tag/v4.1.0
