### ISSUE TITLE
Incrementally adding unwanted line breaks in attributes with curly brackets.

### ISSUE THREAD

**Issue by timitee** [ember-template-lint/ember-template-lint-plugin-prettier#68]
An extra line break is added on each formatting of an attribute with curlies - when longer than the max line width. 

Example:

```
<div class="lots of classes but we are using tailwindcss so that is the nature of things especially when you have a lot of wind {{this.conditionalClass}}">
   Some stuff
</div>
```

Prettier the 1st time. Perfect!:

```
<div class="lots of classes but we are using tailwindcss so that is the nature of things especially when you have a lot of wind 
   {{this.conditionalClass}}">
   Some stuff
</div>
```

Prettier the 2nd time:

```
<div class="lots of classes but we are using tailwindcss so that is the nature of things especially when you have a lot of wind 

   {{this.conditionalClass}}">
   Some stuff
</div>
```

Prettier the 3rd time:

```
<div class="lots of classes but we are using tailwindcss so that is the nature of things especially when you have a lot of wind

 
   {{this.conditionalClass}}">
   Some stuff
</div>
```

Prettier the 4th time:

```
<div class="lots of classes but we are using tailwindcss so that is the nature of things especially when you have a lot of wind

 

   {{this.conditionalClass}}">
   Some stuff
</div>
```

And so on. It's a niggle :)

Thanks for the great plugin BTW.

**Comment by dcyriller** [comment]
Thanks @timitee for reporting this issue!

This is a bug in Prettier 1.19.*... that has been fixed (is it here? https://github.com/prettier/prettier/pull/7051) but not released yet.

1.18.* is okay, I'd recommend using these versions for now.

**Comment by timitee** [comment]
@dcyriller Thanks for the response. I should have realised this was prettier issue, rather than the plugin. I appreciate you taking the time to let me know. Yes. It seems this issue is related. I have an Emberised workaround now so the length is not a problem. But I will wait for the next release and try my issue again when it is. 

Thanks again. I'll close this.
