### ISSUE TITLE
Tilde syntax to remove whitespace.

### ISSUE THREAD

**Issue by jfrux** [ember-template-lint/ember-template-lint-plugin-prettier#72]
```
<div class="details">
  {{~t "player.ads_overlay.ad"~}}
  {{~this.sep~}}
  <span class="ad-place">
    {{~this.adPlacement~}}
  </span>
</div>
```

It won't let me do this, trying to understand how to tell it to ignore this but I still want it to warn me about other things...?

**Comment by dcyriller** [comment]
You can try to add `{{! prettier-ignore }}` on the lines preceding the tildes.

```hbs
<div class="details">
  {{! prettier-ignore }}
  {{~t "player.ads_overlay.ad"~}}
  {{! prettier-ignore }}
  {{~this.sep~}}
  <span class="ad-place">
    {{! prettier-ignore }}
    {{~this.adPlacement~}}
  </span>
</div>
```

Or you can add the file to a `.prettierignore' file?

**Comment by dcyriller** [comment]
That said, I'm looking at Prettier code and see that the ~ should be preserved (see [here](https://github.com/prettier/prettier/blob/2.0.2/src/language-handlebars/printer-glimmer.js#L204)).

Could you share here the output of `yarn prettier --write --parser=glimmer YOUR_FILE`?

**Comment by dcyriller** [comment]
This issue looks on Prettier side (not this template-lint plugin). I'm closing for now.
