### ISSUE TITLE
ALE always complains about newline at end of file

### ISSUE THREAD

**Issue by jamescdavis** [ember-template-lint/ember-template-lint-plugin-prettier#83]
Even when a template file has no newline at the end of file, `ember-template-lint-plugin-prettier` complains when used with ALE. This is because ALE always terminates the last line of the temp file it passes to `ember-template-lint` with a newline.

https://github.com/dense-analysis/ale/pull/3144 fixes this.

**Comment by jamescdavis** [comment]
Note: this seems to also occur when reading from STDIN (https://github.com/dense-analysis/ale/pull/2622).

**Comment by jamescdavis** [comment]
I just looked at how STDIN piping works and it in fact uses a temp file and so https://github.com/dense-analysis/ale/pull/3144 will fix this for https://github.com/dense-analysis/ale/pull/2622 as well! The combination of these two PRs makes things work well without a need for #82 (and will end up better config file overrides support).

**Comment by dcyriller** [comment]
Thanks for investigating this @jamescdavis
It looks it will have to be fixed on ALE side. I'm closing for now.

**Comment by jamescdavis** [comment]
Hopefully we'll see some movement on ALE PRs at some point.

**Comment by jamescdavis** [comment]
Just noting that https://github.com/dense-analysis/ale/pull/3144 has been merged so this issue has been resolved in ALE (but not released as of yet).

**Comment by dcyriller** [comment]
Awesome!
