### ISSUE TITLE
How to make it work well with eslint-plugin-hbs?

### ISSUE THREAD

**Issue by EvgenyOrekhov** [ember-template-lint/ember-template-lint-plugin-prettier#96]
I'm trying to set up ember-template-lint-plugin-prettier and eslint-plugin-hbs together.
The duet works, but not as well as I would like.

Given this perfectly formatted code:

```js
module("module description", function () {
  test("test description", async function () {
    await render(
      hbs`
        <MyComponent
          @foo={{this.foo}}
          @bar={{this.bar}}
          @baz={{this.baz}}
          @qux={{this.qux}}
        />
      `
    );
  });
});
```

ember-template-lint-plugin-prettier wants me to write it like this:

```js
module("module description", function () {
  test("test description", async function () {
    await render(
      hbs`<MyComponent
  @foo={{this.foo}}
  @bar={{this.bar}}
  @baz={{this.baz}}
  @qux={{this.qux}}
/>`
    );
  });
});
```

Which is not good.

Is it possible to somehow configure the plugins to work well together?

Or was it a bad idea to try it and I should wait for https://github.com/prettier/prettier/pull/8647?

**Comment by dcyriller** [comment]
Indeed, the PR you mentioned should make that possible.

**Comment by EvgenyOrekhov** [comment]
Marking this issue as a bad idea. Waiting for the `hbs` tagged templates support in Prettier.
